# Generated by Django 5.0.1 on 2024-01-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DummyApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='fine_charges',
        ),
        migrations.RemoveField(
            model_name='member',
            name='type',
        ),
        migrations.AddField(
            model_name='member',
            name='fine_charged',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
